name: grivit-library - build

on:
  push:
    branches:
      - '**'
      - "!main"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ECR_REGISTRY: ${{ vars.AWS_ECR_REGISTRY }}
  AWS_ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY_GRIVIT_KCL_LIBRARY_PACKAGE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: print ENVs
        run: env

      - name: install aws
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      
      - name: verify the identity being used
        run: aws sts get-caller-identity

      - name: install kcl
        run: wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash

      - name: create kcl package
        run: |
          cd grivit-library
          kcl mod pkg --target pkg
      
      - name: list created kcl package
        run: ls -lah grivit-library/pkg
