name: Deployment

on:
  push:
    branches:
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install 
        run: wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash

      - name: create package
        run: |
          cd grivit-library
          kcl mod pkg --target pkg
      
      - name: list created package
        run: ls -lah grivit-library/pkg
